### ISSUE TITLE
Doesn't work in Windows 10.

### ISSUE THREAD

**Issue by eheisman** [eheisman/dssrip#16]
Something about Windows 10 appears to be causing problem with the DSS onLoad.R functions.  dssrip fails to load, or fails to install because of the 'metadata' tables it uses to do introspection on the java objects it gets back from the DSS Java API.

**Comment by tfitzhughilx** [comment]
Hi, did you have any success fixing this in Windows 10?  I use this package frequently and am switching to a  Windows 10 computer.  Thank you,

**Comment by eheisman** [comment]
I should update this issue.  It does appear to work on Windows 10.  I'm not 100% clear what fixed it, but I believe it was an issue with anti-virus software that was causing it.

**Comment by tfitzhughilx** [comment]
OK cool thanks for the info.  I'm also having issue installing on Windows 10.  When I use the command: 
devtools::install_github("eheisman/DSS-Rip",args="--no-multiarch")  

I get this error: 
Installation failed: Unknown option: ssl.verifypeer  

thanks again

**Comment by eheisman** [comment]
That sounds like a problem in the devtools package.
