### ISSUE TITLE
Can we have an option to turn off `print(metadata)` in `tsc.to.xts()` function?

### ISSUE THREAD

**Issue by tungmilan** [eheisman/dssrip#22]
Hi Evan,

I noticed that after [this commit](https://github.com/eheisman/dssrip/commit/c5e4a6dde9c460c33c73d7542ebcc4478424245e#diff-a47a5a486bb0c31bb01df0576cff35e2), there was a `print(metadata)` added. I think it's useful if only one pathname is read. In my case, I have thousands of pathnames thus it slows down the data retrieval process. I'm wondering if you could add an option to turn it off in  `tsc.to.xts` function? Something like this would do it I believe

```
tsc.to.xts <- function(tsc, colnamesSource = "parameter", offsetForType = FALSE, printMetadata = NULL) {
  
  metadata = getMetadata(tsc, colnamesSource = colnamesSource)
  if (is.null(printMetadata)) {
    print(metadata)
  }
  
}
```

Thanks!

**Comment by eheisman** [comment]
Fixed with recent commit  #(cb0a7b7).  This was a print statement added for debugging and shouldn't have been left in there.
