### ISSUE TITLE
Update required libraries

### ISSUE THREAD

**Issue by tungmilan** [eheisman/dssrip#23]
Hi Evan,

The installation will fail if `xts`, `rjson` and `broom` are not installed. Can you update the README? Thanks!

**Comment by eheisman** [comment]
Fixed with commit  `f81aa41`

**Comment by tungmilan** [comment]
Thanks @eheisman ! By the way, using `install_github()` from [`remotes`](https://cran.r-project.org/web/packages/remotes/index.html) package is more parsimonious because it only has 4 dependencies `methods, stats, tools, utils` while having the same functionality.  

> Download and install R packages stored in GitHub, GitLab, Bitbucket, Bioconductor, or plain subversion or git repositories. This package is a lightweight replacement of the install_* functions in devtools. Indeed most of the code was copied over from devtools.

[`devtools`](https://cran.r-project.org/web/packages/devtools/index.html) requires a lot more packages which `dssrip` users might not need.

> callr (≥ 3.4.4), cli (≥ 2.0.2), covr (≥ 3.5.1), desc (≥ 1.2.0), DT (≥ 0.15), ellipsis (≥ 0.3.1), httr (≥ 1.4.2), jsonlite (≥ 1.7.1), memoise (≥ 1.1.0), pkgbuild (≥ 1.1.0), pkgload (≥ 1.1.0), rcmdcheck (≥ 1.3.3), remotes (≥ 2.2.0), rlang (≥ 0.4.7), roxygen2 (≥ 7.1.1), rstudioapi (≥ 0.11), rversions (≥ 2.0.2), sessioninfo (≥ 1.1.1), stats, testthat (≥ 2.3.2), tools, utils, withr (≥ 2.2.0)

**Comment by eheisman** [comment]
Thanks - I wasn't aware of that package.  `devtools` occasionally gives me headaches with virus protection flagging it as a problem, maybe `remotes` will fix that.
