### ISSUE TITLE
data.table and rJava conlict on J() function

### ISSUE THREAD

**Issue by eheisman** [eheisman/dssrip#4]
Choose an order to import them, or build as package and hide both.

**Comment by eheisman** [comment]
@cameronbracken - do you care if I remove the `data.table` dependency from this package?  I'm doing some serious cleanup and I want to rewrite how it retrieves timeseries.  I'm planning to just offer output to `xts` and the base `data.frame` formats, which the user can then convert.

**Comment by cameronbracken** [comment]
Fine with me

**Comment by eheisman** [comment]
Fixed in "tidyup" branch.
